package com.example.entity;

import io.quarkus.hibernate.orm.panache.PanacheEntityBase;
import jakarta.persistence.*;
import io.quarkus.runtime.annotations.RegisterForReflection;
import lombok.Getter; // Import the Lombok Getter annotation
import lombok.Setter; // You might also need a setter depending on your logic

@Entity
@Table(name = "repositorio_archivos")
@RegisterForReflection
@Getter
@Setter
public class RepositorioArchivo extends PanacheEntityBase {

    @Id
    @Column(name = "id")
    public Long id;

    @Column(nullable = false)
    public String nombre;

    @Column
    public String cuil;

    @Column(nullable = false)
    public String descripcion;

    @Column
    public String metadata;

    @Column(name = "inscripcion_id")
    public Long inscripcionId;

    @Column(name = "instancia_sede_id")
    public Long instanciaSedeId;

    @Column
    public Integer estado;

    // The getters (e.g., getId()) will be automatically generated by Lombok
}